# SPDX-FileCopyrightText: 2024 FaultyRAM <316014+FaultyRAM@users.noreply.github.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "infinite-money-printer-core"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
